function pad2(n){return String(n).padStart(2,'0')}
function addHoursToHM(hm, add){var p=(hm||'00:00').split(':'),h=parseInt(p[0],10)||0,m=parseInt(p[1],10)||0;var d=new Date(2000,0,1,h,m,0,0);d.setHours(d.getHours()+add);return pad2(d.getHours())+':'+pad2(d.getMinutes())}
function rub(n){ return (Math.max(0,Math.round(n))||0).toLocaleString('ru-RU') + ' ₽'; }
function showToast(message, duration){ if(duration===undefined) duration=3000; var toast=document.getElementById('kb-toast'); if(!toast) return; toast.textContent=message; toast.classList.add('kb-toast-visible'); setTimeout(function(){ toast.classList.remove('kb-toast-visible'); }, duration); }
function formatPhone(input){ const value=input.value.replace(/\D/g,''); let formatted='+7 '; if(value.length>1){ const rest=value.substring(1); if(rest.length>0){ formatted+=rest.substring(0,3);} if(rest.length>3){ formatted+=' '+rest.substring(3,6);} if(rest.length>6){ formatted+=' '+rest.substring(6,8);} if(rest.length>8){ formatted+=' '+rest.substring(8,10);} } input.value=formatted; }

var CFG={ HOLIDAYS: [], WINDOWS:[{start:'09:00'},{start:'13:00'},{start:'17:00'},{start:'21:00'}], SLOT_HOURS:3, PRICE_WEEKDAY:7000, PRICE_WEEKEND:8000, DEPOSIT_WEEKDAY:25000, DEPOSIT_WEEKEND:30000, BASE_GUESTS:1 };
function isWeekend(dateStr){if(!dateStr) return false;var d=new Date(dateStr);var day=d.getDay();return day===0||day===6}
function isHoliday(dateStr){if(!dateStr) return false;return CFG.HOLIDAYS.indexOf(dateStr)>=0}
function isWeekendOrHoliday(dateStr){return isWeekend(dateStr)||isHoliday(dateStr)}

document.addEventListener('DOMContentLoaded',function(){
  var dateEl=document.getElementById('kb-date'), hoursEl=document.getElementById('kb-hours'), guestsEl=document.getElementById('kb-guests'), hoursBadge=document.getElementById('kb-hours-badge'), guestsBadge=document.getElementById('kb-guests-badge'), winSeg=document.getElementById('kb-window'), startLabel=document.getElementById('kb-start-label'), totalEl=document.getElementById('kb-total'), depRange=document.getElementById('kb-deposit'), depBadge=document.getElementById('kb-deposit-badge'), depNote=document.getElementById('kb-deposit-note'), noteLine=document.getElementById('kb-note-line'), bookBtn=document.getElementById('kb-book-btn'), nameEl=document.getElementById('kb-name'), phoneEl=document.getElementById('kb-phone');

  // min date = today
  var today=new Date(), yyyy=today.getFullYear(), mm=('0'+(today.getMonth()+1)).slice(-2), dd=('0'+today.getDate()).slice(-2); if(dateEl) dateEl.min=yyyy+'-'+mm+'-'+dd;

  if(phoneEl){ phoneEl.value='+7 '; phoneEl.addEventListener('input', function(){ formatPhone(phoneEl); }); phoneEl.addEventListener('blur', function(){ if(phoneEl.value==='+7 ') phoneEl.value=''; }); phoneEl.addEventListener('focus', function(){ if(!phoneEl.value || !phoneEl.value.startsWith('+7')) phoneEl.value='+7 '; }); }

  var selectedStart=null;
  function fill(range){var min=+range.min||0,max=+range.max||100,val=+range.value||0;var pct=((val-min)*100)/(max-min);range.style.setProperty('--kb-fill',pct+'%')}
  function hoursMaxForStart(){ if(selectedStart===null) return 12; var maxSlots=4-selectedStart; return Math.min(12,maxSlots*CFG.SLOT_HOURS); }
  function clampHours(){ var max=hoursMaxForStart(); hoursEl.max=String(max); var v=+hoursEl.value||CFG.SLOT_HOURS; v=Math.max(CFG.SLOT_HOURS,Math.min(max,v)); v=Math.round(v/CFG.SLOT_HOURS)*CFG.SLOT_HOURS; hoursEl.value=String(v); }
  function applySlotHighlight(slots){ winSeg.querySelectorAll('button').forEach(function(b){b.classList.remove('kb-active','kb-linked');b.setAttribute('aria-selected','false')}); if(selectedStart===null||slots<=0) return; for(var i=0;i<slots;i++){ var btn=winSeg.querySelector('button[data-index="'+(selectedStart+i)+'"]'); if(!btn) break; (i===0?btn.classList.add('kb-active'):btn.classList.add('kb-linked')); btn.setAttribute('aria-selected','true'); } }
  function recompute(){ clampHours(); fill(hoursEl); fill(guestsEl); var durPaid=+hoursEl.value||CFG.SLOT_HOURS; var slots=Math.max(1,Math.round(durPaid/CFG.SLOT_HOURS)); var weekend0=isWeekendOrHoliday(dateEl.value); var baseDep0=weekend0?CFG.DEPOSIT_WEEKEND:CFG.DEPOSIT_WEEKDAY; var price0=weekend0?CFG.PRICE_WEEKEND:CFG.PRICE_WEEKDAY; if(selectedStart===null){ applySlotHighlight(0); startLabel.textContent='—'; hoursBadge.textContent=String(durPaid); noteLine.textContent='Выберите слоты'; var guests0=+guestsEl.value||CFG.BASE_GUESTS; var effGuests0=Math.max(guests0,2); var baselineRemaining=Math.max(baseDep0-(effGuests0*price0*1),0); depRange.max=String(baseDep0); depRange.value=String(baselineRemaining); fill(depRange); depBadge.textContent=rub(baselineRemaining); depNote.textContent='Осталось на процедуры: '+rub(baselineRemaining); totalEl.textContent=rub(baseDep0); return;} applySlotHighlight(slots); var startHM=CFG.WINDOWS[selectedStart].start; startLabel.textContent=startHM; var gift=Math.max(slots-1,0); var endFact=addHoursToHM(startHM,durPaid+gift); if(endFact==='24:00') endFact='00:00'; hoursBadge.textContent=String(durPaid+gift); noteLine.textContent='Вы выбрали: '+startHM+' — '+endFact+(gift?('; +'+gift+' ч в подарок'):''); }
  function recalcMoney(){ var weekend=isWeekendOrHoliday(dateEl.value); var baseDeposit=weekend?CFG.DEPOSIT_WEEKEND:CFG.DEPOSIT_WEEKDAY; if(selectedStart===null){ var guestsInit=+guestsEl.value||CFG.BASE_GUESTS; var effGuestsInit=Math.max(guestsInit,2); var priceInit=weekend?CFG.PRICE_WEEKEND:CFG.PRICE_WEEKDAY; var baselineRemaining=Math.max(baseDeposit-(effGuestsInit*priceInit*1),0); depRange.max=String(baseDeposit); depRange.value=String(baselineRemaining); fill(depRange); depBadge.textContent=rub(baselineRemaining); depNote.textContent='Осталось на процедуры: '+rub(baselineRemaining); totalEl.textContent=rub(baseDeposit); return;} var durPaid=+hoursEl.value||CFG.SLOT_HOURS; var slots=Math.max(1,Math.round(durPaid/CFG.SLOT_HOURS)); var guests=+guestsEl.value||CFG.BASE_GUESTS; var price=weekend?CFG.PRICE_WEEKEND:CFG.PRICE_WEEKDAY; var deposit=baseDeposit*slots; var ticketsReal=guests*price*slots; var ticketsEffective=Math.max(guests,2)*price*slots; var topup=Math.max(deposit-ticketsEffective,0); var total=Math.max(ticketsReal,deposit); depRange.max=String(deposit); depRange.value=String(Math.round(topup)); fill(depRange); depBadge.innerHTML=rub(topup); depNote.innerHTML=topup>0?('Осталось на процедуры: '+rub(topup)):'Билеты перекрывают депозит'; totalEl.innerHTML=rub(total); }
  function handleSlotClick(e){ var btn=e.target.closest('button'); if(!btn) return; var index=btn.getAttribute('data-index'); if(index===null) return; selectedStart=parseInt(index); recompute(); recalcMoney(); showToast('Выбран слот '+CFG.WINDOWS[selectedStart].start); }

  winSeg.addEventListener('click', handleSlotClick);
  hoursEl.addEventListener('input',function(){ recompute(); recalcMoney(); hoursBadge.classList.add('kb-flash'); setTimeout(function(){hoursBadge.classList.remove('kb-flash')},220); });
  guestsEl.addEventListener('input',function(){ guestsBadge.textContent=guestsEl.value; fill(guestsEl); recalcMoney(); guestsBadge.classList.add('kb-flash'); setTimeout(function(){guestsBadge.classList.remove('kb-flash')},220); });
  dateEl.addEventListener('change',function(){ if(!dateEl.value){ showToast('Пожалуйста, выберите дату',3000); dateEl.classList.add('kb-input-error'); return;} dateEl.classList.remove('kb-input-error'); recompute(); recalcMoney(); });
  document.getElementById('kb-book-btn').addEventListener('click',function(e){ e.preventDefault(); if(!dateEl.value){ showToast('Пожалуйста, выберите дату',3000); dateEl.classList.add('kb-input-error'); return;} if(selectedStart===null){ showToast('Выберите хотя бы один слот',3000); winSeg.classList.add('kb-input-error'); setTimeout(function(){ winSeg.classList.remove('kb-input-error') },1000); return;} if(!nameEl.value.trim()){ showToast('Введите ваше имя',3000); nameEl.classList.add('kb-input-error'); nameEl.focus(); return;} if(!phoneEl.value.trim()){ showToast('Введите номер телефона',3000); phoneEl.classList.add('kb-input-error'); phoneEl.focus(); return;} var date=dateEl.value?dateEl.value.split('-').reverse().join('.'):'не выбрана'; var durPaid=+hoursEl.value||CFG.SLOT_HOURS; var slots=Math.max(1,Math.round(durPaid/CFG.SLOT_HOURS)); var gift=Math.max(slots-1,0); var startHM=CFG.WINDOWS[selectedStart].start; var endHM=addHoursToHM(startHM,durPaid+gift); if(endHM==='24:00') endHM='00:00'; var lines=['Заявка на бронирование — Калиновая Баня','Дата: '+date,'Интервал: '+startHM+'–'+endHM,'Гостей: '+(guestsEl.value||'—'),'Телефон: '+(phoneEl&&phoneEl.value?phoneEl.value.trim():'—'),'Имя: '+(nameEl&&nameEl.value?nameEl.value.trim():'—'),'Итого к оплате: '+(document.getElementById('kb-total').textContent)]; var text=encodeURIComponent(lines.join('\n')); window.open('https://wa.me/79347771777?text='+text,'_blank'); });
  document.querySelectorAll('#kb-window button').forEach(function(btn){ var top=btn.querySelector('.kb-slot-start'); var bot=btn.querySelector('.kb-slot-end'); var st=top.textContent.trim(); var end=addHoursToHM(st,CFG.SLOT_HOURS); if(bot){ bot.textContent='до '+(end==='24:00'?'00:00':end); } });
  try{ fetch('https://api.open-meteo.com/v1/forecast?latitude=43.6833&longitude=40.2000&current=temperature_2m,weather_code&timezone=auto',{cache:'no-store'}).then(function(r){return r.json()}).then(function(d){ var t=(d&&d.current&&typeof d.current.temperature_2m==='number')?Math.round(d.current.temperature_2m):null; var tNode=document.getElementById('kb-temp'); if(tNode) tNode.textContent=(t==null?'—':t)+'°'; }).catch(function(){}) }catch(_){ }
});

// Toggle open/close using :target and hash
(function(){
  var CARD_ID='kb-booking'; var card; function isOpen(){ return !!card && card.matches(':target'); }
  function setBody(){ document.body.classList.toggle('kb-open', isOpen()); if(window.innerWidth<=600){ if(isOpen()){ document.body.style.top='-'+window.scrollY+'px'; } else { var scrollY=document.body.style.top; document.body.style.top=''; window.scrollTo(0, parseInt(scrollY||'0')*-1); } } }
  function openCard(){ try{ location.hash='#'+CARD_ID; }catch(_){ window.location.href='#'+CARD_ID; } setTimeout(setBody,0); }
  function closeCard(){ try{ location.hash=''; }catch(_){} if(location.hash){ try{ history.replaceState(null, document.title, window.location.pathname+window.location.search);}catch(_){}} if(location.hash){ try{ window.location.href=window.location.pathname+window.location.search;}catch(_){}} setTimeout(setBody,0); }
  window.addEventListener('hashchange', setBody);
  document.addEventListener('DOMContentLoaded', function(){ card=document.getElementById(CARD_ID); setBody(); var fab=document.querySelector('#kb-widget .kb-fab'); if(fab){ fab.addEventListener('click', function(e){ e.preventDefault(); if(isOpen()) closeCard(); else openCard(); }, true);} var closeBtn=document.querySelector('#kb-booking .kb-close'); if(closeBtn){ closeBtn.addEventListener('click', function(e){ e.preventDefault(); closeCard(); }, true);} window.addEventListener('resize', function(){ if(window.innerWidth>600 && document.body.classList.contains('kb-open')){ document.body.classList.remove('kb-open'); document.body.style.top=''; } }); });
})();

